# Generated by Django 6.0.5 on 2026-06-23 18:38

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('workos_organization_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='PermissionCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('group', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['group', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('workos_role_slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('requires_office', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_owner', models.BooleanField(default=False)),
                ('workos_user_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.company')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyOffice',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('office_type', models.CharField(choices=[('OWN', 'Own Office'), ('PARTNER', 'Partner Office'), ('MANUAL', 'Manual Office')], default='OWN', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$', 'Invalid Indian GSTIN format.')])),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('scope_type', models.CharField(choices=[('COMPANY', 'Company'), ('BRANCH', 'Branch')], default='COMPANY', max_length=30)),
                ('scope_id', models.CharField(blank=True, max_length=26, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_offices', to='core.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Office',
                'verbose_name_plural': 'Company Offices',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.companyoffice'),
        ),
        migrations.CreateModel(
            name='GlobalOffice',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='global_offices', to='core.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_global_offices', to='core.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='companyoffice',
            name='global_office',
            field=models.ForeignKey(blank=True, help_text='Discovery/import source only. Runtime operations never reference GlobalOffice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_copies', to='core.globaloffice'),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')])),
                ('address', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$', 'Invalid Indian GSTIN format.')])),
                ('scope_type', models.CharField(choices=[('COMPANY', 'Company'), ('BRANCH', 'Branch')], default='COMPANY', max_length=30)),
                ('scope_id', models.CharField(blank=True, max_length=26, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='core.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRolePermissionOverride',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('scope', models.CharField(choices=[('own', 'Own'), ('branch', 'Branch'), ('region', 'Region'), ('company', 'Company'), ('all', 'All')], default='branch', max_length=20)),
                ('based_on_template_revision', models.PositiveIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_overrides', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_overrides', to='core.permissioncatalog')),
            ],
            options={
                'ordering': ['company', 'role', 'permission__code'],
            },
        ),
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['role', '-revision'],
                'constraints': [models.UniqueConstraint(fields=('role', 'revision'), name='unique_role_template_revision')],
            },
        ),
        migrations.CreateModel(
            name='RoleTemplatePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('own', 'Own'), ('branch', 'Branch'), ('region', 'Region'), ('company', 'Company'), ('all', 'All')], default='branch', max_length=20)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_grants', to='core.permissioncatalog')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='core.roletemplate')),
            ],
            options={
                'ordering': ['template__role', 'permission__code'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Standard state code (e.g., MH, KA)', max_length=5, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.state'),
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(max_length=50)),
                ('workos_organization_membership_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('workos_role_slug', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.companyoffice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='unique_lower_username'),
        ),
        migrations.AddIndex(
            model_name='globaloffice',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='global_office_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='globaloffice',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('city'), name='unique_global_office_name_city'),
        ),
        migrations.AddIndex(
            model_name='companyoffice',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='company_office_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='companyoffice',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'COMPANY')), fields=('company', 'name', 'scope_type'), name='unique_company_scope_office'),
        ),
        migrations.AddConstraint(
            model_name='companyoffice',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'BRANCH')), fields=('company', 'name', 'scope_type', 'scope_id'), name='unique_branch_scope_office'),
        ),
        migrations.AddConstraint(
            model_name='companyoffice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_id__isnull', True), ('scope_type', 'COMPANY')), models.Q(models.Q(('scope_type', 'COMPANY'), _negated=True), ('scope_id__isnull', False)), _connector='OR'), name='office_scope_id_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('phone'), models.F('company'), models.F('scope_type'), condition=models.Q(('scope_type', 'COMPANY')), name='unique_company_scope_party'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('phone'), models.F('company'), models.F('scope_type'), models.F('scope_id'), condition=models.Q(('scope_type', 'BRANCH')), name='unique_branch_scope_party'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_id__isnull', True), ('scope_type', 'COMPANY')), models.Q(models.Q(('scope_type', 'COMPANY'), _negated=True), ('scope_id__isnull', False)), _connector='OR'), name='party_scope_id_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='companyrolepermissionoverride',
            constraint=models.UniqueConstraint(fields=('company', 'role', 'permission'), name='unique_company_role_permission_override'),
        ),
        migrations.AddConstraint(
            model_name='roletemplatepermission',
            constraint=models.UniqueConstraint(fields=('template', 'permission'), name='unique_role_template_permission'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('name', 'state'), name='unique_city_per_state'),
        ),
        migrations.AddConstraint(
            model_name='usermembership',
            constraint=models.UniqueConstraint(fields=('user', 'company', 'office', 'role'), name='unique_user_membership'),
        ),
    ]
