# Generated by Django 6.0.5 on 2026-06-03 13:26

import core.models
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('PLATFORM_ADMIN', 'Platform Admin'), ('CLIENT_SUPER_ADMIN', 'Client Super Admin'), ('BRANCH_ADMIN', 'Branch Admin'), ('BOOKING_USER', 'Booking User'), ('DELIVERY_USER', 'Delivery User'), ('ACCOUNTANT', 'Accountant'), ('VIEWER', 'Viewer')], max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='party',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_branch_per_company'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('phone'), models.F('company'), name='unique_party_per_company'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.branch'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.company'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usermembership',
            constraint=models.UniqueConstraint(fields=('user', 'company', 'branch', 'role'), name='unique_user_membership'),
        ),
        migrations.AddConstraint(
            model_name='usermembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__in', ['BRANCH_ADMIN', 'BOOKING_USER', 'DELIVERY_USER']), _negated=True), ('branch__isnull', False), _connector='OR'), name='active_branch_required_for_operational_roles'),
        ),
    ]
