# Generated by Django 6.0.5 on 2026-06-14 11:53

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_office_admin_to_branch_admin'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='companyoffice',
            name='unique_office_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='party',
            name='unique_party_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='usermembership',
            name='office_required_for_operational_roles',
        ),
        migrations.AddField(
            model_name='companyoffice',
            name='scope_id',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='companyoffice',
            name='scope_type',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('BRANCH', 'Branch')], default='COMPANY', max_length=30),
        ),
        migrations.AddField(
            model_name='party',
            name='scope_id',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='scope_type',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('BRANCH', 'Branch')], default='COMPANY', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='companyoffice',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'COMPANY')), fields=('company', 'name', 'scope_type'), name='unique_company_scope_office'),
        ),
        migrations.AddConstraint(
            model_name='companyoffice',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'BRANCH')), fields=('company', 'name', 'scope_type', 'scope_id'), name='unique_branch_scope_office'),
        ),
        migrations.AddConstraint(
            model_name='companyoffice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_id__isnull', True), ('scope_type', 'COMPANY')), models.Q(models.Q(('scope_type', 'COMPANY'), _negated=True), ('scope_id__isnull', False)), _connector='OR'), name='office_scope_id_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('phone'), models.F('company'), models.F('scope_type'), condition=models.Q(('scope_type', 'COMPANY')), name='unique_company_scope_party'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('phone'), models.F('company'), models.F('scope_type'), models.F('scope_id'), condition=models.Q(('scope_type', 'BRANCH')), name='unique_branch_scope_party'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_id__isnull', True), ('scope_type', 'COMPANY')), models.Q(models.Q(('scope_type', 'COMPANY'), _negated=True), ('scope_id__isnull', False)), _connector='OR'), name='party_scope_id_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='usermembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__in', ['BRANCH_ADMIN', 'BOOKING_USER', 'DELIVERY_USER', 'ACCOUNTANT', 'VIEWER']), _negated=True), ('office__isnull', False), _connector='OR'), name='office_required_for_operational_roles'),
        ),
    ]
