# Generated by Django 6.0.5 on 2026-06-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usermembership_alter_party_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
