# Generated by Django 6.0.5 on 2026-06-01 18:10

import core.models
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('docket_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('BOOKED', 'Booked'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('INCOMING', 'Incoming')], default='DRAFT', max_length=50)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('idempotency_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('basis', models.CharField(choices=[('WEIGHT', 'Weight'), ('FIXED', 'Fixed'), ('UNIT', 'Unit')], default='WEIGHT', max_length=50)),
                ('payment_type', models.CharField(choices=[('PAID', 'Paid'), ('TO_PAY', 'To Pay'), ('TBB', 'TBB (To Be Billed)')], default='PAID', max_length=50)),
                ('mode', models.CharField(choices=[('ROAD', 'Road'), ('AIR', 'Air'), ('TRAIN', 'Train'), ('SEA', 'Sea')], default='ROAD', max_length=50)),
                ('delivery_type', models.CharField(choices=[('DOOR', 'Door Delivery'), ('OFFICE', 'Office Collection')], default='DOOR', max_length=50)),
                ('consignor_name', models.CharField(max_length=100)),
                ('consignor_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')])),
                ('consignor_address', models.TextField()),
                ('consignee_name', models.CharField(max_length=100)),
                ('consignee_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')])),
                ('consignee_address', models.TextField()),
                ('gst_party', models.CharField(max_length=100)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$', 'Invalid Indian GSTIN format.')])),
                ('notes', models.TextField(blank=True, null=True)),
                ('freight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('additional_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('final_freight', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('freight'), '+', models.F('additional_charges')), '+', models.F('delivery_charge')), output_field=models.DecimalField(decimal_places=2, max_digits=10))),
                ('advance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remaining_balance', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('freight'), '+', models.F('additional_charges')), '+', models.F('delivery_charge')), '-', models.F('advance_amount')), output_field=models.DecimalField(decimal_places=2, max_digits=10))),
                ('total_packages', models.PositiveIntegerField(default=0)),
                ('total_actual_weight', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_charge_weight', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dockets', to='core.company')),
                ('consignee_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.city')),
                ('consignor_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_dockets', to='core.branch')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.city')),
                ('origin_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_dockets', to='core.branch')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.city')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docket',
                'verbose_name_plural': 'Dockets',
                'ordering': ['-date', '-created_at'],
                'permissions': [('view_all_branches', 'Can view dockets from all branches'), ('add_docket_all_branches', 'Can add dockets for all branches'), ('reassign_all_branches', 'Can reassign docket origin/destination to any branch')],
            },
        ),
        migrations.CreateModel(
            name='DocketLineItem',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_type', models.CharField(choices=[('GENERAL', 'General'), ('HAZARDOUS', 'Hazardous'), ('PERISHABLE', 'Perishable'), ('FRAGILE', 'Fragile')], default='GENERAL', max_length=50)),
                ('package_type', models.CharField(choices=[('BOX', 'Box'), ('BAG', 'Bag'), ('CRATE', 'Crate'), ('BUNDLE', 'Bundle'), ('PALLET', 'Pallet')], default='BOX', max_length=50)),
                ('rate_type', models.CharField(choices=[('PER_KG', 'Per Kg'), ('PER_PIECE', 'Per Piece'), ('FLAT', 'Flat Rate')], default='PER_KG', max_length=50)),
                ('pieces', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('actual_weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('charged_weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('charge', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('docket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='dockets.docket')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docket Line Item',
                'verbose_name_plural': 'Docket Line Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DocketSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('last_value', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Docket Sequence',
                'verbose_name_plural': 'Docket Sequences',
            },
        ),
        migrations.AddIndex(
            model_name='docket',
            index=models.Index(fields=['company', 'is_active', '-date'], name='idx_tenant_active_date'),
        ),
        migrations.AddIndex(
            model_name='docket',
            index=models.Index(fields=['company', 'docket_no'], name='idx_tenant_docket_no'),
        ),
        migrations.AddIndex(
            model_name='docket',
            index=models.Index(fields=['origin_branch', 'is_active'], name='idx_origin_active'),
        ),
        migrations.AddIndex(
            model_name='docket',
            index=models.Index(fields=['destination_branch', 'is_active'], name='idx_dest_active'),
        ),
        migrations.AddIndex(
            model_name='docket',
            index=models.Index(fields=['company', 'status'], name='idx_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='docket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['consignor_name'], name='consignor_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='docket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['consignee_name'], name='consignee_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='docket',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('company', 'idempotency_key'), name='unique_company_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='docket',
            constraint=models.UniqueConstraint(fields=('company', 'docket_no'), name='unique_company_docket_no'),
        ),
        migrations.AddConstraint(
            model_name='docket',
            constraint=models.CheckConstraint(condition=models.Q(('freight__gte', 0)), name='freight_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='docket',
            constraint=models.CheckConstraint(condition=models.Q(('additional_charges__gte', 0)), name='additional_charges_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='docket',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_charge__gte', 0)), name='delivery_charge_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='docket',
            constraint=models.CheckConstraint(condition=models.Q(('advance_amount__gte', 0)), name='advance_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='docket',
            constraint=models.CheckConstraint(condition=models.Q(('total_actual_weight__gte', 0)), name='total_actual_weight_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='docket',
            constraint=models.CheckConstraint(condition=models.Q(('total_charge_weight__gte', 0)), name='total_charge_weight_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='docket',
            constraint=models.CheckConstraint(condition=models.Q(('final_freight__gte', 0)), name='final_freight_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='docket',
            constraint=models.CheckConstraint(condition=models.Q(('advance_amount__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('freight'), '+', models.F('additional_charges')), '+', models.F('delivery_charge')))), name='advance_amount_lte_final_freight'),
        ),
        migrations.AddConstraint(
            model_name='docketlineitem',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='docketlineitem',
            constraint=models.CheckConstraint(condition=models.Q(('charge__gte', 0)), name='charge_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='docketlineitem',
            constraint=models.CheckConstraint(condition=models.Q(('pieces__gte', 1)), name='pieces_gte_1'),
        ),
        migrations.AlterUniqueTogether(
            name='docketsequence',
            unique_together={('company', 'date')},
        ),
    ]
