# Generated by Django 6.0.5 on 2026-06-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockets', '0002_docketlineitem_override_reason_branchratepolicy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='consignee_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docket',
            name='consignor_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
