# Generated by Django 6.0.5 on 2026-06-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockets', '0003_alter_docket_consignee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='gst_party',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
