# Generated by Django 6.0.5 on 2026-06-08 09:31

import core.models
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeRatePolicy',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_override_rate', models.BooleanField(default=False)),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('requires_approval', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_rate_policies', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate_policy', to='core.companyoffice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='RateRule',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('basis', models.CharField(choices=[('WEIGHT', 'Weight'), ('FIXED', 'Fixed'), ('UNIT', 'Unit')], max_length=50)),
                ('rate_type', models.CharField(choices=[('PER_KG', 'Per Kg'), ('PER_PIECE', 'Per Piece'), ('FLAT', 'Flat Rate')], max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_rules_destination', to='core.city')),
                ('destination_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_rules_destination', to='core.companyoffice')),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_rules_origin', to='core.city')),
                ('origin_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_rules_origin', to='core.companyoffice')),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='shipments.ratecard')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lr_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('BOOKED', 'Booked'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=50)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('idempotency_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('basis', models.CharField(choices=[('WEIGHT', 'Weight'), ('FIXED', 'Fixed'), ('UNIT', 'Unit')], default='WEIGHT', max_length=50)),
                ('payment_type', models.CharField(choices=[('PAID', 'Paid'), ('TO_PAY', 'To Pay'), ('TBB', 'TBB (To Be Billed)')], default='PAID', max_length=50)),
                ('mode', models.CharField(choices=[('ROAD', 'Road'), ('AIR', 'Air'), ('TRAIN', 'Train'), ('SEA', 'Sea')], default='ROAD', max_length=50)),
                ('delivery_type', models.CharField(choices=[('DOOR', 'Door Delivery'), ('OFFICE', 'Office Collection')], default='DOOR', max_length=50)),
                ('consignor_name', models.CharField(max_length=100)),
                ('consignor_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')])),
                ('consignor_address', models.TextField(blank=True, null=True)),
                ('consignee_name', models.CharField(max_length=100)),
                ('consignee_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')])),
                ('consignee_address', models.TextField(blank=True, null=True)),
                ('gst_party', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$', 'Invalid Indian GSTIN format.')])),
                ('notes', models.TextField(blank=True, null=True)),
                ('freight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('additional_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('final_freight', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('freight'), '+', models.F('additional_charges')), '+', models.F('delivery_charge')), output_field=models.DecimalField(decimal_places=2, max_digits=10))),
                ('advance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remaining_balance', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('freight'), '+', models.F('additional_charges')), '+', models.F('delivery_charge')), '-', models.F('advance_amount')), output_field=models.DecimalField(decimal_places=2, max_digits=10))),
                ('total_packages', models.PositiveIntegerField(default=0)),
                ('total_actual_weight', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_charge_weight', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.company')),
                ('consignee_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.city')),
                ('consignor_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destination_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_shipments', to='core.companyoffice')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.city')),
                ('origin_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_shipments', to='core.companyoffice')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.city')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'permissions': [('view_all_offices', 'Can view shipments from all offices'), ('add_shipment_all_offices', 'Can add shipments for all offices'), ('reassign_all_offices', 'Can reassign shipment origin/destination to any office')],
            },
        ),
        migrations.CreateModel(
            name='ProofOfDelivery',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('received_by_name', models.CharField(max_length=100)),
                ('received_by_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')])),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pod', to='shipments.shipment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('delivery_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignments', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.CharField(choices=[('BOOKED', 'Booked'), ('DISPATCHED', 'Dispatched'), ('RECEIVED', 'Received'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_events', to='core.companyoffice')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipments.shipment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLineItem',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_type', models.CharField(choices=[('GENERAL', 'General'), ('HAZARDOUS', 'Hazardous'), ('PERISHABLE', 'Perishable'), ('FRAGILE', 'Fragile')], default='GENERAL', max_length=50)),
                ('package_type', models.CharField(choices=[('BOX', 'Box'), ('BAG', 'Bag'), ('CRATE', 'Crate'), ('BUNDLE', 'Bundle'), ('PALLET', 'Pallet')], default='BOX', max_length=50)),
                ('rate_type', models.CharField(choices=[('PER_KG', 'Per Kg'), ('PER_PIECE', 'Per Piece'), ('FLAT', 'Flat Rate')], default='PER_KG', max_length=50)),
                ('pieces', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('actual_weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('charged_weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('charge', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('rate_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='shipments.raterule')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='shipments.shipment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('last_value', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['company', 'is_active', '-date'], name='idx_shipment_tenant_date'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['company', 'lr_no'], name='idx_tenant_lr_no'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['origin_office', 'is_active'], name='idx_origin_office_active'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['destination_office', 'is_active'], name='idx_dest_office_active'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['company', 'status'], name='idx_shipment_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['consignor_name'], name='shipment_consignor_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['consignee_name'], name='shipment_consignee_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('company', 'idempotency_key'), name='unique_company_shipment_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('company', 'lr_no'), name='unique_company_lr_no'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(condition=models.Q(('advance_amount__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('freight'), '+', models.F('additional_charges')), '+', models.F('delivery_charge')))), name='advance_amount_lte_shipment_final_freight'),
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['shipment', '-occurred_at'], name='idx_shipment_event_time'),
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['office', 'event_type'], name='idx_event_office_type'),
        ),
        migrations.AlterUniqueTogether(
            name='shipmentsequence',
            unique_together={('company', 'date')},
        ),
    ]
