"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path
from urllib.parse import unquote, urlparse
from dotenv import load_dotenv
from import_export.formats.base_formats import CSV, XLSX

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(BASE_DIR / '.env')


def require_env(name):
    value = os.environ.get(name)
    if not value:
        raise ImportError(f"The {name} environment variable is required.")
    return value


def require_bool(name):
    value = require_env(name).lower()
    if value not in ('1', 'true', 'yes', 'on', '0', 'false', 'no', 'off'):
        raise ImportError(f"The {name} environment variable must be true or false.")
    return value in ('1', 'true', 'yes', 'on')


def get_url_host(url):
    parsed = urlparse(url)
    return parsed.hostname


def join_url(base_url, path):
    return f"{base_url.rstrip('/')}/{path.lstrip('/')}"


def unique(items):
    return list(dict.fromkeys(items))


def database_from_url(name):
    url = require_env(name)
    parsed = urlparse(url)
    if parsed.scheme not in ('postgres', 'postgresql', 'postgresql+psycopg'):
        raise ImportError(f"{name} must use a postgres:// or postgresql:// URL.")

    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote(parsed.path.lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or 5432),
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = require_env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = require_bool('DJANGO_DEBUG')

FRONTEND_URL = require_env('FRONTEND_URL').rstrip('/')
BACKEND_URL = require_env('BACKEND_URL').rstrip('/')
REDIS_URL = require_env('REDIS_URL')

BACKEND_HOST = get_url_host(BACKEND_URL)
if not BACKEND_HOST:
    raise ImportError("BACKEND_URL must be an absolute URL with a hostname.")

ALLOWED_HOSTS = [BACKEND_HOST]
if DEBUG:
    ALLOWED_HOSTS = unique(ALLOWED_HOSTS + ['localhost', '127.0.0.1', '::1'])


# Application definition

# Celery Configuration
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

if 'pytest' in sys.modules or 'test' in sys.argv:
    CELERY_TASK_ALWAYS_EAGER = True

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'pgtrigger',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'import_export',
    'core',
    'authentication',
    'shipments',
    'accounts',
]

IMPORT_EXPORT_USE_TRANSACTIONS = True
IMPORT_EXPORT_IMPORT_IGNORE_BLANK_LINES = True
IMPORT_EXPORT_ESCAPE_FORMULAE_ON_EXPORT = True
IMPORT_EXPORT_ESCAPE_ILLEGAL_CHARS_ON_EXPORT = True
IMPORT_EXPORT_FORMATS = [CSV, XLSX]
IMPORT_FORMATS = [CSV, XLSX]
EXPORT_FORMATS = [CSV, XLSX]
IMPORT_EXPORT_MAX_UPLOAD_SIZE = int(os.environ.get('IMPORT_EXPORT_MAX_UPLOAD_SIZE', 10 * 1024 * 1024))

AUTH_USER_MODEL = 'core.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.ActiveContextJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/minute',
        'user': '1000/hour',
        'login_attempts': '5/min',
        'otp_attempts': '5/min',
        'signup_attempts': '5/hour',
    },
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 100,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

WORKOS_API_KEY = require_env('WORKOS_API_KEY')
WORKOS_CLIENT_ID = require_env('WORKOS_CLIENT_ID')
WORKOS_AUTO_PROVISION_USERS = False
WORKOS_AUDIT_LOGS_ENABLED = os.environ.get('WORKOS_AUDIT_LOGS_ENABLED', 'false').lower() in ('1', 'true', 'yes', 'on')
WORKOS_ROLE_SLUGS = {
    'SUPER_ADMIN': os.environ.get('WORKOS_SUPER_ADMIN_ROLE_SLUG', 'admin'),
    'BRANCH_ADMIN': os.environ.get('WORKOS_BRANCH_ADMIN_ROLE_SLUG', ''),
    'BOOKING_USER': os.environ.get('WORKOS_BOOKING_USER_ROLE_SLUG', ''),
    'DELIVERY_USER': os.environ.get('WORKOS_DELIVERY_USER_ROLE_SLUG', ''),
    'ACCOUNTANT': os.environ.get('WORKOS_ACCOUNTANT_ROLE_SLUG', ''),
    'VIEWER': os.environ.get('WORKOS_VIEWER_ROLE_SLUG', ''),
    'METRO': os.environ.get('WORKOS_METRO_ROLE_SLUG', ''),
}
DEFAULT_FROM_EMAIL = (
    os.environ.get('DEFAULT_FROM_EMAIL')
    or os.environ.get('BOOTSTRAP_OWNER_EMAIL')
    or 'webmaster@localhost'
)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
METRO_SIGNUP_REVIEW_URL = join_url(FRONTEND_URL, '/admin/users')
WORKOS_ROLE_MAPPING = {
    'metro': 'METRO',
    'owner': 'SUPER_ADMIN',
    'admin': 'SUPER_ADMIN',
    'super-admin': 'SUPER_ADMIN',
    'super_admin': 'SUPER_ADMIN',
    'manager': 'BRANCH_ADMIN',
    'branch-admin': 'BRANCH_ADMIN',
    'branch_admin': 'BRANCH_ADMIN',
    'booking': 'BOOKING_USER',
    'booking-user': 'BOOKING_USER',
    'booking_user': 'BOOKING_USER',
    'delivery': 'DELIVERY_USER',
    'delivery-user': 'DELIVERY_USER',
    'delivery_user': 'DELIVERY_USER',
    'accountant': 'ACCOUNTANT',
    'viewer': 'VIEWER',
}
AUTHENTICATION_BACKENDS = (
    'authentication.backends.CaseInsensitiveModelBackend',
    'django.contrib.auth.backends.ModelBackend',
)


MIDDLEWARE = [
    'core.middleware.RequestIDMiddleware',
    'core.middleware.RequestContextMiddleware',
    'core.middleware.ExceptionLoggingMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.TenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.RequestMethodMiddleware',
]

# LR format: {DD}{MM}{YY}{SEQ:3} to match requests like DDMMYY398.
LR_FORMAT = '{DD}{MM}{YY}{SEQ:3}'

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [FRONTEND_URL]
CORS_ALLOW_HEADERS = [
    'accept',
    'authorization',
    'content-type',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-idempotency-key',
    'x-use-primary-db',
    'x-company-id',
    'x-office-id',
]


ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': database_from_url('DATABASE_URL'),
}

if os.environ.get('REPLICA_DATABASE_URL'):
    replica_database = database_from_url('REPLICA_DATABASE_URL')
    replica_database['TEST'] = {'MIRROR': 'default'}
    DATABASES['replica'] = replica_database

import sys

DATABASE_ROUTERS = ['core.routers.PrimaryReplicaRouter'] if 'replica' in DATABASES else []
if 'pytest' in sys.modules or 'test' in sys.argv:
    DATABASE_ROUTERS = []

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'IGNORE_EXCEPTIONS': True,
        },
    },
    'throttle': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'IGNORE_EXCEPTIONS': True,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-in'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = 'd/m/Y H:i:s'
SHORT_DATE_FORMAT = 'd/m/Y'
DATE_INPUT_FORMATS = ['%d/%m/%Y', '%d-%m-%Y', '%Y-%m-%d']
DATETIME_INPUT_FORMATS = ['%d/%m/%Y %H:%M:%S', '%d/%m/%Y %H:%M', '%Y-%m-%d %H:%M:%S']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
