# Generated by Django 6.0.5 on 2026-07-05 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authauditlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_audit_events', to='core.company'),
        ),
        migrations.AddField(
            model_name='authauditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_auth_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_signup_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_requests', to='core.company'),
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_signup_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='authauditlog',
            index=models.Index(fields=['event_type', 'status', 'created_at'], name='authenticat_event_t_d657fe_idx'),
        ),
        migrations.AddIndex(
            model_name='authauditlog',
            index=models.Index(fields=['workos_user_id'], name='authenticat_workos__43f268_idx'),
        ),
        migrations.AddIndex(
            model_name='authauditlog',
            index=models.Index(fields=['workos_organization_id'], name='authenticat_workos__09bf1c_idx'),
        ),
        migrations.AddIndex(
            model_name='signuprequest',
            index=models.Index(fields=['status', 'created_at'], name='authenticat_status_7e05b5_idx'),
        ),
        migrations.AddIndex(
            model_name='signuprequest',
            index=models.Index(fields=['email'], name='authenticat_email_b83d59_idx'),
        ),
        migrations.AddIndex(
            model_name='signuprequest',
            index=models.Index(fields=['workos_user_id'], name='authenticat_workos__00f709_idx'),
        ),
    ]
