# Generated by Django 6.0.5 on 2026-07-05 20:36

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprequest',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='UsernameEmailLookup',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['username'],
                'indexes': [models.Index(django.db.models.functions.text.Lower('email'), name='auth_userlookup_email_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='unique_lower_auth_username_lookup')],
            },
        ),
    ]
