# Generated by Codex on 2026-07-03

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupRequest",
            fields=[
                ("id", models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("company_name", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], default="PENDING", max_length=20)),
                ("workos_user_id", models.CharField(blank=True, max_length=100)),
                ("workos_organization_id", models.CharField(blank=True, max_length=100)),
                ("workos_organization_membership_id", models.CharField(blank=True, max_length=100)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_signup_requests", to=settings.AUTH_USER_MODEL)),
                ("company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="signup_requests", to="core.company")),
                ("rejected_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="rejected_signup_requests", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="signup_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="signuprequest",
            index=models.Index(fields=["status", "created_at"], name="authenticat_status_7e05b5_idx"),
        ),
        migrations.AddIndex(
            model_name="signuprequest",
            index=models.Index(fields=["email"], name="authenticat_email_b83d59_idx"),
        ),
        migrations.AddIndex(
            model_name="signuprequest",
            index=models.Index(fields=["workos_user_id"], name="authenticat_workos__00f709_idx"),
        ),
    ]
