# Generated by Django 6.0.5 on 2026-07-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_signuprequest_username_usernameemaillookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuprequest',
            name='status',
            field=models.CharField(choices=[('EMAIL_VERIFICATION_PENDING', 'Email verification pending'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=32),
        ),
    ]
